### ISSUE TITLE
Tables don't have horizontal or vertical lines

### ISSUE THREAD

**Issue by johnblommers** [guilhermeprokisch/smd#2]
Table rendering is too minimalistic, as there are no vertical and horizontal lines surrounding the rows and columns.

More like this:

| Col 1 | Col 2 |
| ----- | ----- |
| Row 1 | Row 1 |
| Row 2 | Row 2 |

**Comment by guilhermeprokisch** [comment]
It was intentional plan most for support blocked text like the `smd --help`

<img width="717" alt="image" src="https://github.com/user-attachments/assets/a289183f-c68b-412d-9e2b-a596485cd2f3">

but should be optional add some borders in the the future.

**Comment by guilhermeprokisch** [comment]
@johnblommers  add this as optional in v0.2.10  but you should add to your config file now. Take a look at
 https://github.com/guilhermeprokisch/smd?tab=readme-ov-file#configuration

<img width="1331" alt="image" src="https://github.com/user-attachments/assets/3cee5a08-b05c-4b8f-89f1-31f514dfeeef">
