### ISSUE TITLE
--version flag broken under Windows build

### ISSUE THREAD

**Issue by graphixillusion** [guilhermeprokisch/smd#4]
Hi there. As the topic says using the windows build when you launch 

smd --version 

this will happen:

Error: Os { code: 2, kind: NotFound, message: "Unable to find specified file" }

**Comment by guilhermeprokisch** [comment]
👋 Hey

Yes, already have a patch coming for this one. 

Thanks

**Comment by guilhermeprokisch** [comment]
Should be fixed on version https://github.com/guilhermeprokisch/smd/releases/tag/v0.2.9
